#pragma once
#define M1 "MetroLine1.txt"
#define M2 "MetroLine2.txt"
#define M3 "MetroLine3.txt"
#define M4 "MetroLine4.txt"
#define M5 "MetroLine5.txt"
#define M7 "MetroLine7.txt"
#define M10 "MetroLine10.txt"
#define S1 "MetroLineS1.txt"
#define S3 "MetroLineS3.txt"
#define S6 "MetroLineS6.txt"
#define S7 "MetroLineS7.txt"
#define S8 "MetroLineS8.txt"
#define S9 "MetroLineS9.txt"
#define Time "Time.txt"
#define Info "E:/C++/编程训练/ATM存取一体系统/Info.txt"
#define Water "E:/C++/编程训练/ATM存取一体系统/water.txt"